name: 'Setup Node.js with Dependencies'
description: 'Setup Node.js, cache and install dependencies (requires checkout first)'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  registry-url:
    description: 'NPM registry URL (for publish job)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - uses: actions/cache@v4
      id: node-modules
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-${{ runner.os }}-

    - if: steps.node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
