name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Set up test with '...'
        2. Run test with '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Expected the test to pass with...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The test failed with...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      placeholder: |
        ```typescript
        test.performance({
          thresholds: { base: { duration: 500, rerenders: 20 } }
        })('test name', async ({ page, performance }) => {
          // ...
        });
        ```
      render: typescript

  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of react-performance-tracking are you using?
      placeholder: e.g., 0.1.1
    validations:
      required: true

  - type: input
    id: react-version
    attributes:
      label: React Version
      description: What version of React are you using?
      placeholder: e.g., 18.3.1

  - type: input
    id: playwright-version
    attributes:
      label: Playwright Version
      description: What version of Playwright are you using?
      placeholder: e.g., 1.46.1

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 18.20.0
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you testing with?
      options:
        - Chromium
        - Firefox
        - WebKit
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does this issue occur?
      options:
        - Local development
        - CI (GitHub Actions)
        - CI (Other)
        - Both local and CI
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs or console output
      placeholder: Paste error logs here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, artifacts, etc.)
